// Auto-generated by fnrpc. DO NOT EDIT.
// This file has been generated by Specta. Do not edit this file manually.
export type BigInput = {
	id: bigint,
	big: bigint,
	list: bigint[],
};

/**
 *  An RPC error returned by any handler (query, mutate, subscribe).
 * 
 *  Maps to [`RpcError`](https://docs.rs/fnrpc-client/latest/fnrpc_client/class.RpcError.html)
 *  in the TypeScript client.
 * 
 *  # TS mirror
 * 
 *  ```typescript
 *  class RpcError extends Error {
 *    name: "RpcErr";
 *    code: string;
 *    message: string;
 *    data: unknown;
 *  }
 *  ```
 */
export type RpcErr = {
	name: string,
	code: string,
	message: string,
	data: unknown | null,
};

export type TickInput = {
	start: bigint,
	count: bigint,
};

export type Procedures = {
  big_echo: { kind: "query"; method: "GET"; input: BigInput; output: string; error: RpcErr };
  big_echo_primitive: { kind: "query"; method: "GET"; input: bigint; output: string; error: RpcErr };
  big_echo_primitive_post: { kind: "query"; method: "GET"; input: bigint; output: string; error: RpcErr };
  big_echo_primitive_mutate: { kind: "mutate"; method: "POST"; input: bigint; output: string; error: RpcErr };
  big_echo_mutate: { kind: "mutate"; method: "POST"; input: BigInput; output: string; error: RpcErr };
  tick_seq: { kind: "subscribe"; method: "GET"; input: TickInput; output: string; error: RpcErr };
}

export const __procedureMeta = {
  big_echo: { kind: "query", method: "GET" },
  big_echo_primitive: { kind: "query", method: "GET" },
  big_echo_primitive_post: { kind: "query", method: "GET" },
  big_echo_primitive_mutate: { kind: "mutate", method: "POST" },
  big_echo_mutate: { kind: "mutate", method: "POST" },
  tick_seq: { kind: "subscribe", method: "GET" },
} as const;
