// Auto-generated by fnrpc. DO NOT EDIT.
// This file has been generated by Specta. Do not edit this file manually.
export type BigInput = {
	id: bigint,
	big: bigint,
	list: bigint[],
};

export type BigOutput = {
	id: bigint,
	big: bigint,
	list: bigint[],
};

/**  `rename_all = "camelCase"`: the wire key is `userId`, not `user_id`. */
export type CamelInput = {
	userId: bigint,
	total: bigint,
};

/**
 *  `#[serde(flatten)]`: the inner struct's fields are hoisted onto the outer
 *  object, so `inner` never appears as a key on the wire.
 */
export type FlatInner = {
	big: bigint,
};

export type FlatInput = {
	tag: string,
} & FlatInner;

export type NewtypeInput = {
	id: UserId,
};

/**
 *  Externally tagged enum: serde puts the payload *under the variant name*,
 *  so `Small(u64)` is `{"Small": ...}` on the wire.
 */
export type Payload = ({ Small: bigint }) & { Named?: never } | ({ Named: {
	big: bigint,
} }) & { Small?: never };

/**
 *  An RPC error returned by any handler (query, mutate, subscribe).
 * 
 *  Maps to [`RpcError`](https://docs.rs/fnrpc-client/latest/fnrpc_client/class.RpcError.html)
 *  in the TypeScript client.
 * 
 *  # TS mirror
 * 
 *  ```typescript
 *  class RpcError extends Error {
 *    name: "RpcErr";
 *    code: string;
 *    message: string;
 *    data: unknown;
 *  }
 *  ```
 */
export type RpcErr = {
	name: string,
	code: string,
	message: string,
	data: unknown,
};

export type TickInput = {
	start: bigint,
	count: bigint,
};

export type TickOutput = {
	n: bigint,
};

/**
 *  Newtype: serde serialises it transparently, so `UserId(u64)` is a bare
 *  number with no wrapper to index into.
 */
export type UserId = bigint;

/**
 *  Generic: the BigInt lives in the type *argument*, which the generic
 *  definition itself never mentions.
 */
export type Wrapper<T> = {
	v: T,
	label: string,
};

export type Procedures = {
  big_echo: { kind: "query"; method: "GET"; input: BigInput; output: BigInput; error: RpcErr };
  big_echo_primitive: { kind: "query"; method: "GET"; input: bigint; output: string; error: RpcErr };
  big_echo_primitive_post: { kind: "query"; method: "POST"; input: bigint; output: string; error: RpcErr };
  big_echo_primitive_mutate: { kind: "mutate"; method: "POST"; input: bigint; output: string; error: RpcErr };
  big_echo_mutate: { kind: "mutate"; method: "POST"; input: BigInput; output: BigInput; error: RpcErr };
  big_out: { kind: "query"; method: "GET"; input: null; output: BigOutput; error: RpcErr };
  camel_echo: { kind: "mutate"; method: "POST"; input: CamelInput; output: CamelInput; error: RpcErr };
  flat_echo: { kind: "mutate"; method: "POST"; input: FlatInput; output: FlatInput; error: RpcErr };
  wrapper_echo: { kind: "mutate"; method: "POST"; input: Wrapper<bigint>; output: Wrapper<bigint>; error: RpcErr };
  payload_echo: { kind: "mutate"; method: "POST"; input: Payload; output: Payload; error: RpcErr };
  newtype_echo: { kind: "mutate"; method: "POST"; input: NewtypeInput; output: NewtypeInput; error: RpcErr };
  tick_seq: { kind: "subscribe"; method: "GET"; input: TickInput; output: TickOutput; error: RpcErr };
  tick_seq_post: { kind: "subscribe"; method: "POST"; input: TickInput; output: TickOutput; error: RpcErr };
  zh_input: { kind: "query"; method: "GET"; input: string; output: string; error: RpcErr };
  zh_input_post: { kind: "query"; method: "POST"; input: string; output: string; error: RpcErr };
}

export const __procedureMeta = {
  big_echo: { kind: "query", method: "GET" },
  big_echo_primitive: { kind: "query", method: "GET" },
  big_echo_primitive_post: { kind: "query", method: "POST" },
  big_echo_primitive_mutate: { kind: "mutate", method: "POST" },
  big_echo_mutate: { kind: "mutate", method: "POST" },
  big_out: { kind: "query", method: "GET" },
  camel_echo: { kind: "mutate", method: "POST" },
  flat_echo: { kind: "mutate", method: "POST" },
  wrapper_echo: { kind: "mutate", method: "POST" },
  payload_echo: { kind: "mutate", method: "POST" },
  newtype_echo: { kind: "mutate", method: "POST" },
  tick_seq: { kind: "subscribe", method: "GET" },
  tick_seq_post: { kind: "subscribe", method: "POST" },
  zh_input: { kind: "query", method: "GET" },
  zh_input_post: { kind: "query", method: "POST" },
} as const;
