import type { ProcedureKind, Procedure, Procedures } from "./types";

/**
 * Override a procedure's kind to a specific value.
 *
 * Useful when narrowing a generic `Procedure` type.
 */
export type ProcedureWithKind<V extends ProcedureKind> = Omit<
  Procedure,
  "kind"
> & { kind: V };

/**
 * Resolve to `void` if the procedure input is `null`, otherwise `Else`.
 *
 * This enables the idiomatic `client.fn()` calling convention for
 * procedures that take no arguments.
 */
export type VoidIfInputNull<
  P extends Procedure,
  Else = P["input"],
> = P["input"] extends null ? void : Else;

/**
 * The callable signature for a single procedure.
 *
 * - Subscribe procedures return `Promise<AsyncIterable<output>>`.
 * - Query/mutate procedures return `Promise<output>`.
 *
 * Both accept an optional `AbortSignal` as the second argument
 * (after input).
 */
export type ProcedureCallable<P extends Procedure> =
  P["kind"] extends "subscribe"
    ? (input: VoidIfInputNull<P>, signal?: AbortSignal) => Promise<AsyncIterable<P["output"]>>
    : (input: VoidIfInputNull<P>, signal?: AbortSignal) => Promise<P["output"]>;

/** The typed client proxy type, mirroring the `Procedures` shape. */
type ClientProceduresProxy<P extends Procedures> = {
  [K in keyof P]: P[K] extends Procedure
    ? ProcedureCallable<P[K]>
    : P[K] extends Procedures
      ? ClientProceduresProxy<P[K]>
      : never;
};

/** The type-safe client. Every procedure is a callable method. */
export type Client<P extends Procedures> = ClientProceduresProxy<P>;

/**
 * Transport function signature.
 *
 * Implement this to create a custom backend (e.g. WebSocket, custom HTTP).
 *
 * @param path - Dot-separated procedure path (e.g. `"users.get"`).
 * @param input - Serialised JSON input.
 * @param kind - `"query"`, `"mutate"`, or `"subscribe"`.
 * @param signal - Optional abort signal for cancellation.
 * @param method - HTTP method override (`"GET"` or `"POST"`).
 */
type Transport = (
  path: string,
  input: unknown,
  kind: ProcedureKind,
  signal?: AbortSignal,
  method?: string,
) => Promise<unknown>;

type ProcedureMeta = {
  kind: ProcedureKind;
  method: string;
};

const noop = () => {
  // noop
};

/**
 * Create a recursive `Proxy` that builds paths as properties are accessed,
 * then calls a callback when invoked as a function.
 *
 * Internal helper used by [`createClient`].
 */
export function createProceduresProxy<T>(
  callback: (opts: { path: string[]; args: any[] }) => unknown,
  path: string[] = [],
): T {
  return new Proxy(noop, {
    get(_, key) {
      if (typeof key !== "string") return;

      return createProceduresProxy(callback, [...path, key]);
    },
    apply(_1, _2, args) {
      return callback({ args, path });
    },
  }) as T;
}

/**
 * Create a typed fnrpc client.
 *
 * @param transport - Transport function (e.g. [`fetchTransport`] or [`tauriTransport`]).
 * @param metaMap - Runtime metadata map generated by codegen (`__procedureMeta`).
 *
 * @example
 * ```typescript
 * import { createClient, fetchTransport } from "@fnrpc/client";
 * import type { Procedures } from "./bindings";
 * import { __procedureMeta } from "./bindings";
 *
 * export const fnrpc = createClient<Procedures>(fetchTransport({ url: "http://localhost:3000/fnrpc" }), __procedureMeta);
 * ```
 */
export function createClient<P extends Procedures>(
  transport: Transport,
  metaMap: Record<string, ProcedureMeta>,
): Client<P> {
  return createProceduresProxy<Client<P>>(({ args, path }) => {
    const pathStr = path.join(".");
    const meta = metaMap[pathStr];
    if (!meta) throw new Error(`Unknown procedure: ${pathStr}`);
    return transport(pathStr, args[0], meta.kind, args[1], meta.method);
  });
}

/**
 * Generate a TanStack Query-compatible query key for a procedure.
 *
 * @deprecated Use [`ProcedureUtils.queryKey`] from `@fnrpc/tanstack-query` instead.
 */
export function getQueryKey(
  path: string,
  input: unknown,
): [string] | [string, unknown] {
  return input === undefined ? [path] : [path, input];
}

/**
 * Traverse a deeply-nested client proxy to reach a procedure at a given path.
 *
 * Internal helper used by [`ProcedureUtils`](https://docs.rs/fnrpc-tanstack-query).
 */
export function traverseClient(
  client: Client<any>,
  path: string[],
): (...args: any[]) => any {
  let ret: any = client;

  for (const segment of path) {
    ret = ret[segment];
  }

  return ret as any;
}
