/** Join two path segments with `.`, skipping the empty prefix. */
export type JoinPath<
  TPath extends string,
  TNext extends string,
> = TPath extends "" ? TNext : `${TPath}.${TNext}`;

/**
 * The kind of an RPC procedure.
 *
 * - `"query"`: idempotent read, typically `GET`.
 * - `"mutate"`: state-changing write, typically `POST`.
 * - `"subscribe"`: long-lived SSE stream of events.
 */
export type ProcedureKind = "query" | "mutate" | "subscribe";

/**
 * A single RPC procedure type descriptor — the core type primitive.
 *
 * Generated by the codegen for each procedure.
 */
export type Procedure = {
  kind: ProcedureKind;
  input: unknown;
  output: unknown;
  error: { code: string; message: string; data?: unknown };
};

/**
 * A recursive map of procedure paths to their type descriptors.
 *
 * Nested `Procedures` objects represent sub-routers, leaf values are
 * [`Procedure`] entries.
 */
export type Procedures = {
  [K in string]: Procedure | Procedures;
};

/**
 * A discriminated result type — either success or typed error.
 */
export type Result<Ok, Err> =
  | { status: "ok"; data: Ok }
  | { status: "err"; error: Err };

/** Convenience alias: [`Result`] parameterized by a [`Procedure`]. */
export type ProcedureResult<P extends Procedure> = Result<
  P["output"],
  P["error"]
>;

/** Options for [`consumeEventIterator`]. */
export type ConsumeEventOptions<T, E> = {
  onEvent?: (value: T) => void;
  onError?: (err: E) => void;
  onComplete?: () => void;
  onFinish?: () => void;
};
