// Auto-generated by fnrpc. DO NOT EDIT.
// This file has been generated by Specta. Do not edit this file manually.
export type User = {
	id: number,
	name: string,
	email: string,
};
export type Procedures = {
  greet: { kind: "query"; input: string; output: string; error: unknown };
  create_user: { kind: "mutation"; input: [string, string]; output: User; error: unknown };
  get_user: { kind: "query"; input: number; output: User; error: unknown };
  add: { kind: "query"; input: [number, number]; output: number; error: unknown };
  get_count: { kind: "query"; input: null; output: string; error: unknown };
  health_check: { kind: "query"; input: null; output: string; error: unknown };
  divide: { kind: "query"; input: [number | null, number | null]; output: number | null; error: unknown };
  tick: { kind: "subscription"; input: bigint; output: bigint; error: unknown };
  echo_stream: { kind: "subscription"; input: string; output: string; error: unknown };
  watch_status: { kind: "subscription"; input: string; output: string; error: unknown };
}
