// Auto-generated by fnrpc. DO NOT EDIT.
// This file has been generated by Specta. Do not edit this file manually.
export type User = {
	id: number,
	name: string,
	email: string,
};
export type Procedures = {
  add: { kind: "query"; input: [number, number]; output: number; error: string };
  health_check: { kind: "query"; input: null; output: string; error: string };
  divide: { kind: "query"; input: [number | null, number | null]; output: number | null; error: string };
  create_user: { kind: "mutate"; input: [string, string]; output: User; error: string };
  greet: { kind: "query"; input: string; output: string; error: string };
  get_user: { kind: "query"; input: number; output: User; error: string };
  get_count: { kind: "query"; input: null; output: string; error: string };
  tick: { kind: "subscribe"; input: bigint; output: bigint; error: string };
  watch_status: { kind: "subscribe"; input: string; output: string; error: string };
  echo_stream: { kind: "subscribe"; input: string; output: string; error: string };
}

export const __procedureKinds = {
  add: "query",
  health_check: "query",
  divide: "query",
  create_user: "mutate",
  greet: "query",
  get_user: "query",
  get_count: "query",
  tick: "subscribe",
  watch_status: "subscribe",
  echo_stream: "subscribe",
} as const;
