//! TypeScript code generation.
//!
//! Generates a `bindings.ts` file with:
//!
//! - All specta-exported type definitions
//! - A `Procedures` interface for full type-safe client creation
//! - A `__procedureMeta` runtime map with `{ kind, method }` per path
//!
//! Use [`generate_ts_client`] to get the string, or [`write_ts_client`]
//! to write directly to disk.

use std::path::Path;

use specta::Type;
use specta::datatype::DataType;

use crate::error::RpcErr;
use crate::router::RpcRouter;

/// Generate TypeScript type definitions and a `Procedures` interface.
///
/// The output includes:
///
/// - All specta-exported type definitions for input/output types.
/// - A `Procedures` type mapping each procedure name to its `{ kind, method, input, output, error }`.
/// - A `__procedureMeta` const map used at runtime by the TS client for dispatch.
pub fn generate_ts_client<Ctx: Send + Sync + 'static>(
    router: &RpcRouter<Ctx>,
    _rpc_url: &str,
) -> String {
    // No-op Format — doesn't modify types
    struct NoFmt;
    impl specta::Format for NoFmt {
        fn map_types(
            &self,
            types: &specta::Types,
        ) -> std::result::Result<std::borrow::Cow<'_, specta::Types>, specta::FormatError>
        {
            Ok(std::borrow::Cow::Owned(types.clone()))
        }
        fn map_type(
            &self,
            _types: &specta::Types,
            dt: &DataType,
        ) -> std::result::Result<std::borrow::Cow<'_, DataType>, specta::FormatError>
        {
            Ok(std::borrow::Cow::Owned(dt.clone()))
        }
    }

    // Collect types into a shared type registry
    let mut types = specta::Types::default();
    RpcErr::definition(&mut types);
    for (_, handler) in &router.inner.handlers {
        handler.populate_types(&mut types, &mut vec![]);
    }
    for (_, sub) in &router.inner.subscribes {
        sub.populate_types(&mut types, &mut vec![]);
    }

    // Apply semantic remapping for TS types.
    let semantic =
        specta_typescript::semantic::Configuration::default().enable_lossless_bigints();
    let types = semantic.apply_types(&types);

    // Export all types via the exporter
    let exporter = specta_typescript::Typescript::default()
        .header("// Auto-generated by fnrpc. DO NOT EDIT.");
    let mut out = exporter.export(&types, NoFmt).expect("specta export failed");
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }

    // Build the Procedures interface
    out.push_str("export type Procedures = {\n");
    for (_, handler) in &router.inner.handlers {
        let i = handler.input_ts();
        let o = handler.output_ts();
        let kind = handler.kind();
        let method = if kind == "mutate" { "POST" } else { "GET" };
        out.push_str(&format!(
            "  {}: {{ kind: \"{kind}\"; method: \"{method}\"; input: {}; output: {}; error: RpcErr }};\n",
            handler.name(),
            i.ts_ref,
            o.ts_ref,
        ));
    }
    for (_, sub) in &router.inner.subscribes {
        let i = sub.input_ts();
        let o = sub.output_ts();
        let method = sub.method();
        out.push_str(&format!(
            "  {}: {{ kind: \"subscribe\"; method: \"{method}\"; input: {}; output: {}; error: RpcErr }};\n",
            sub.name(),
            i.ts_ref,
            o.ts_ref,
        ));
    }
    out.push_str("}\n");

    out.push_str("\nexport const __procedureMeta = {\n");
    for (_, handler) in &router.inner.handlers {
        let kind = handler.kind();
        let method = if kind == "mutate" { "POST" } else { "GET" };
        out.push_str(&format!(
            "  {}: {{ kind: \"{kind}\", method: \"{method}\" }},\n",
            handler.name(),
        ));
    }
    for (_, sub) in &router.inner.subscribes {
        let method = sub.method();
        out.push_str(&format!(
            "  {}: {{ kind: \"subscribe\", method: \"{method}\" }},\n",
            sub.name(),
        ));
    }
    out.push_str("} as const;\n");

    out
}

/// Generate and write a TypeScript client file to disk.
///
/// Shortcut for calling [`generate_ts_client`] and writing the result
/// with [`std::fs::write`].
///
/// # Errors
///
/// Returns `io::Error` if the file cannot be written.
pub fn write_ts_client<Ctx: Send + Sync + 'static>(
    router: &RpcRouter<Ctx>,
    rpc_url: &str,
    output_path: &Path,
) -> std::io::Result<()> {
    let content = generate_ts_client(router, rpc_url);
    std::fs::write(output_path, content)
}
