//! TypeScript code generation.
//!
//! Generates a `bindings.ts` file with:
//!
//! - All specta-exported type definitions
//! - A `Procedures` interface for full type-safe client creation
//! - A `__procedureMeta` runtime map with `{ kind, method }` per path
//!
//! Use [`generate_ts_client`] to get the string, or [`write_ts_client`]
//! to write directly to disk.

use std::path::Path;

use specta::Type;
use specta::datatype::{DataType, Primitive, Reference};

use crate::handler::TsTypeInfo;
use crate::router::{ProcedureMeta, RpcRouter};

/// Resolve a specta [`Type`] to a TypeScript type reference string.
pub(crate) fn type_ts<T: Type>() -> TsTypeInfo {
    let mut types = specta::Types::default();
    let data_type = T::definition(&mut types);

    let ts_ref = match &data_type {
        DataType::Struct(_) | DataType::Enum(_) => types
            .into_sorted_iter()
            .next()
            .map(|ndt| ndt.name.to_string())
            .unwrap_or_else(|| "unknown".to_string()),
        DataType::Reference(Reference::Named(r)) => {
            if let Some(ndt) = types.get(r) {
                if ndt.ty.is_some() {
                    ndt.name.to_string()
                } else {
                    let exporter = specta_typescript::Typescript::default();
                    specta_typescript::primitives::inline(&exporter, &types, &data_type)
                        .unwrap_or_else(|_| "unknown".to_string())
                }
            } else {
                "unknown".to_string()
            }
        }
        DataType::Primitive(p)
            if matches!(
                p,
                Primitive::u64
                    | Primitive::i64
                    | Primitive::u128
                    | Primitive::i128
                    | Primitive::usize
                    | Primitive::isize
            ) =>
        {
            "bigint".to_string()
        }
        DataType::Primitive(Primitive::f64) => "number | null".to_string(),
        _ => {
            let exporter = specta_typescript::Typescript::default();
            specta_typescript::primitives::inline(&exporter, &types, &data_type)
                .unwrap_or_else(|_| "unknown".to_string())
        }
    };

    TsTypeInfo { ts_ref }
}

/// Generate TypeScript type definitions and a `Procedures` interface.
///
/// The output includes:
///
/// - All specta-exported type definitions for input/output types.
/// - A `Procedures` type mapping each procedure name to its `{ kind, method, input, output, error }`.
/// - A `__procedureMeta` const map used at runtime by the TS client for dispatch.
pub fn generate_ts_client<Ctx: Send + Sync + 'static>(
    router: &RpcRouter<Ctx>,
    _rpc_url: &str,
) -> String {
    // No-op Format — doesn't modify types
    struct NoFmt;
    impl specta::Format for NoFmt {
        fn map_types(
            &self,
            types: &specta::Types,
        ) -> std::result::Result<std::borrow::Cow<'_, specta::Types>, specta::FormatError>
        {
            Ok(std::borrow::Cow::Owned(types.clone()))
        }
        fn map_type(
            &self,
            _types: &specta::Types,
            dt: &DataType,
        ) -> std::result::Result<std::borrow::Cow<'_, DataType>, specta::FormatError>
        {
            Ok(std::borrow::Cow::Owned(dt.clone()))
        }
    }

    // Collect types into a shared type registry
    let mut types = specta::Types::default();
    // Note: type definitions are already resolved at build time via
    // RpcRouterBuilder::register() and stored in ProcedureMeta.
    // The specta-exported types are reconstructed here from metadata.

    // Apply semantic remapping for TS types.
    let semantic =
        specta_typescript::semantic::Configuration::default().enable_lossless_bigints();
    let types = semantic.apply_types(&types);

    // Export all types via the exporter
    let exporter = specta_typescript::Typescript::default()
        .header("// Auto-generated by fnrpc. DO NOT EDIT.");
    let mut out = exporter.export(&types, NoFmt).expect("specta export failed");
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }

    // Build the Procedures interface
    out.push_str("export type Procedures = {\n");
    for meta in router.procedures() {
        let kind = meta.kind;
        let method = if kind == "mutate" { "POST" } else { "GET" };
        out.push_str(&format!(
            "  {}: {{ kind: \"{kind}\"; method: \"{method}\"; input: {}; output: {}; error: RpcErr }};\n",
            meta.key,
            meta.input.ts_ref,
            meta.output.ts_ref,
        ));
    }
    out.push_str("}\n");

    out.push_str("\nexport const __procedureMeta = {\n");
    for meta in router.procedures() {
        let kind = meta.kind;
        let method = if kind == "mutate" { "POST" } else { "GET" };
        out.push_str(&format!(
            "  {}: {{ kind: \"{kind}\", method: \"{method}\" }},\n",
            meta.key,
        ));
    }
    out.push_str("} as const;\n");

    out
}

/// Generate and write a TypeScript client file to disk.
///
/// Shortcut for calling [`generate_ts_client`] and writing the result
/// with [`std::fs::write`].
///
/// # Errors
///
/// Returns `io::Error` if the file cannot be written.
pub fn write_ts_client<Ctx: Send + Sync + 'static>(
    router: &RpcRouter<Ctx>,
    rpc_url: &str,
    output_path: &Path,
) -> std::io::Result<()> {
    let content = generate_ts_client(router, rpc_url);
    std::fs::write(output_path, content)
}
